version: '3'
services:
  joke:
    image: "docker.io/scadteam2/p07-joke"
    ports:
      - "8000:8000"
  app:
    image: "docker.io/scadteam2/p07-app"
    ports:
      - "8080:8080"
    environment:
       DB_PASSWORD: supersecret
       DB_HOST: mysql_db:3306
       DB_USER: root
       DB_SCHEMA: zhaw
