apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: joke
  name: joke
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: joke
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: joke
    spec:
      containers:
        - image: docker.io/scadteam2/p07-joke
          name: joke
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
